# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ba9add063f3415c37f45d3f79cb8fe43"
name = "remix-app-test-1"
application_url = "https://canon-nightlife-lebanon-produce.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "super-poster-test-store-two.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://canon-nightlife-lebanon-produce.trycloudflare.com/auth/callback",
  "https://canon-nightlife-lebanon-produce.trycloudflare.com/auth/shopify/callback",
  "https://canon-nightlife-lebanon-produce.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
